### ISSUE TITLE
Exclamation mark sprite too tall

### ISSUE THREAD

**Issue by Arc676** [LordKorea/KgF#45]
The exclamation mark sprite used for system messages in the chat is too tall. It overlaps with previous exclamation marks and makes them look like lines.

![marks](https://user-images.githubusercontent.com/30745465/35762879-99e16f48-08da-11e8-9645-e2163cc1146c.jpg)

**Comment by Arc676** [comment]
But for some reason this only happens locally. When I join a game, this appears.

![screen shot](https://user-images.githubusercontent.com/30745465/35773891-040be6e0-099a-11e8-919d-ba78081d5f24.jpg)

**Comment by RealFloorIsJava** [comment]
Can't reproduce.
![cantrep](https://user-images.githubusercontent.com/31963040/36454005-7a17c5e0-169a-11e8-9881-11b61660df7b.png)
